version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: vkfedosov/foodgram_backend:latest
    restart: unless-stopped
    entrypoint: ["bash", "-c", "./entrypoint.sh"]
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: vkfedosov/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - backend
      - frontend

volumes:
  data_value:
  static_value:
  media_value: